global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # EnMapper API metrics
  - job_name: 'enmapper-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # Redis metrics (if redis_exporter is added later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']
    
  # Postgres metrics (if postgres_exporter is added later)  
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']
